### PR TITLE
GH-333: Upgrade to `commons-net-3.4`

### PR DESCRIPTION
**Pull request by artembilan**
Fixes: GH-333

### CODE REVIEW

**Comment by artembilan** [comment]
I think this can be cherry-picked to Platform-2.0 painlessly.

**Comment by wilkinsona** [comment]
> I think this can be cherry-picked to Platform-2.0 painlessly.

It can't, unfortunately. We can't move to a new minor version of Commons Net in a maintenance version of the Platform. This change will have to only be in 2.1.

**Comment by wilkinsona** [comment]
@artembilan Thanks for the PR. The change is now in master.

**Comment by artembilan** [comment]
> This change will have to only be in 2.1.

@wilkinsona , that's fine with us.
I just wondered if end-users will get a gain from the new fixed `commons-net` just after upgrading to the next IO maint version.
OK. We can't, but users can just overriding the version explicitly.

Thank you for taking care about my PR!

**Pull request closed without merging**
