### PR TITLE
GH-218: Add Zookeeper and Curator dependencies

### PR DESCRIPTION
**Pull request by artembilan**
Fixes: https://github.com/spring-io/platform/issues/218

### CODE REVIEW

**Comment by artembilan** [comment]
@wilkinsona , tell me, please, how do you get deal with exclusion for transitive dependencies which we manually exclude in our projects? E.g. for this particular case it is in the SI:
```
compile ("org.apache.zookeeper:zookeeper:$zookeeperVersion")

compile("org.apache.curator:curator-recipes:$curatorVersion") {
	exclude group: 'org.apache.zookeeper', module: 'zookeeper'
	exclude group: 'org.jboss.netty', module: 'netty'
}
```

**Comment by wilkinsona** [comment]
Thanks, Artem. I'll merge this once 2.0.0.M1 has been released. It contains Spring Integration 4.2.0.M1 which doesn't need these dependencies.

The Platform doesn't care about exclusions, it's only interested in managing the versions of dependencies. Projects using the Platform are free to exclude transitive dependencies to meet their needs.

**Comment by artembilan** [comment]
Got it! Thanks, Andy!
Everything makes sense.
Sorry for silly noise  :smile: .

**Comment by wilkinsona** [comment]
I'd overlooked the need for a version of SI that's compatible with Spring Data GemFire 1.7.0. We'll need these dependencies in 2.0.0.M1.

**Comment by wilkinsona** [comment]
Merged in 10ef587a7851cf56921d2606f475cfd14dc0c49c.

**Pull request closed without merging**
